// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexLibrary.Infrastructure.Persistence;

#nullable disable

namespace NexLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexLibraryDbContext))]
    [Migration("20260518101646_AddMissingPermissionDefinitions")]
    partial class AddMissingPermissionDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexLibrary.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("EskiDegerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KayitId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TabloAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("YeniDegerJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KayitId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OlusturmaTarihi");

                    b.HasIndex("TabloAdi");

                    b.ToTable("AuditLoglari", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.DinamikAlanDegeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DinamikAlanDegeriId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool?>("DegerBool")
                        .HasColumnType("bit");

                    b.Property<string>("DegerJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DegerMetin")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("DegerSayi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DegerTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormAlaniId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KayitId")
                        .HasColumnType("int");

                    b.Property<int>("ModulKodu")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormAlaniId");

                    b.HasIndex("ModulKodu", "KayitId");

                    b.HasIndex("ModulKodu", "KayitId", "FormAlaniId")
                        .IsUnique();

                    b.ToTable("DinamikAlanDegerleri", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.FormAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FormAlaniId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AlanKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AlanTipi")
                        .HasColumnType("int");

                    b.Property<bool>("AramadaGorunsunMu")
                        .HasColumnType("bit");

                    b.Property<bool>("BenzersizMi")
                        .HasColumnType("bit");

                    b.Property<bool>("DetaydaGorunsunMu")
                        .HasColumnType("bit");

                    b.Property<bool>("FormdaGorunsunMu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("HizliKayittaGorunsunMu")
                        .HasColumnType("bit");

                    b.Property<bool>("ListedeGorunsunMu")
                        .HasColumnType("bit");

                    b.Property<int?>("MaksimumKarakter")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumKarakter")
                        .HasColumnType("int");

                    b.Property<int>("ModulKodu")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("SilinebilirMi")
                        .HasColumnType("bit");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<bool>("SistemAlaniMi")
                        .HasColumnType("bit");

                    b.Property<bool>("TipDegistirilebilirMi")
                        .HasColumnType("bit");

                    b.Property<string>("VarsayilanDeger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ModulKodu", "AlanKodu")
                        .IsUnique();

                    b.HasIndex("ModulKodu", "SiraNo");

                    b.ToTable("FormAlanlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Kitabın sistemde görünen ana adıdır. Bu alan zorunludur.",
                            AktifMi = true,
                            AlanAdi = "Kitap Adı",
                            AlanKodu = "KITAP_ADI",
                            AlanTipi = 1,
                            AramadaGorunsunMu = true,
                            BenzersizMi = false,
                            DetaydaGorunsunMu = true,
                            FormdaGorunsunMu = true,
                            HizliKayittaGorunsunMu = true,
                            ListedeGorunsunMu = true,
                            MaksimumKarakter = 200,
                            MinimumKarakter = 1,
                            ModulKodu = 1,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Placeholder = "Örn: Nutuk",
                            SilinebilirMi = false,
                            SiraNo = 1,
                            SistemAlaniMi = true,
                            TipDegistirilebilirMi = false,
                            ZorunluMu = true
                        },
                        new
                        {
                            Id = -2,
                            Aciklama = "Üyenin sistemde görünen ad soyad bilgisidir. Bu alan zorunludur.",
                            AktifMi = true,
                            AlanAdi = "Üye Adı Soyadı",
                            AlanKodu = "UYE_ADI_SOYADI",
                            AlanTipi = 1,
                            AramadaGorunsunMu = true,
                            BenzersizMi = false,
                            DetaydaGorunsunMu = true,
                            FormdaGorunsunMu = true,
                            HizliKayittaGorunsunMu = true,
                            ListedeGorunsunMu = true,
                            MaksimumKarakter = 200,
                            MinimumKarakter = 1,
                            ModulKodu = 2,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Placeholder = "Örn: Ahmet Yılmaz",
                            SilinebilirMi = false,
                            SiraNo = 1,
                            SistemAlaniMi = true,
                            TipDegistirilebilirMi = false,
                            ZorunluMu = true
                        });
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KitapId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KitapAdi");

                    b.ToTable("Kitaplar", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.KitapKopya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KitapKopyaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DemirbasNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Barkod")
                        .IsUnique();

                    b.HasIndex("Durum");

                    b.HasIndex("KitapId");

                    b.ToTable("KitapKopyalari", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SifreSalt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Eposta");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KullaniciRolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KullaniciRolleri", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Odunc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OduncId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<int?>("KitapKopyaId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanlananIadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("KitapId");

                    b.HasIndex("KitapKopyaId");

                    b.HasIndex("PlanlananIadeTarihi");

                    b.HasIndex("UyeId");

                    b.ToTable("Oduncler", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RolKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RolKodu")
                        .IsUnique();

                    b.ToTable("Roller", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Sistemde tüm işlemleri yapabilir.",
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolAdi = "Admin",
                            RolKodu = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Kitap, üye, ödünç ve iade işlemlerini yapabilir.",
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolAdi = "Personel",
                            RolKodu = "PERSONEL"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Sadece listeleme, detay ve rapor görüntüleme işlemlerini yapabilir.",
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolAdi = "Görüntüleyici",
                            RolKodu = "GORUNTULEYICI"
                        });
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.RolYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolYetkiId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTanimiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YetkiTanimiId");

                    b.HasIndex("RolId", "YetkiTanimiId")
                        .IsUnique();

                    b.ToTable("RolYetkileri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 1
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 10
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 11
                        },
                        new
                        {
                            Id = 4,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 12
                        },
                        new
                        {
                            Id = 5,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 13
                        },
                        new
                        {
                            Id = 6,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 20
                        },
                        new
                        {
                            Id = 7,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 21
                        },
                        new
                        {
                            Id = 8,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 22
                        },
                        new
                        {
                            Id = 9,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 23
                        },
                        new
                        {
                            Id = 10,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 30
                        },
                        new
                        {
                            Id = 11,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 31
                        },
                        new
                        {
                            Id = 12,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 32
                        },
                        new
                        {
                            Id = 13,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 33
                        },
                        new
                        {
                            Id = 14,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 40
                        },
                        new
                        {
                            Id = 15,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 41
                        },
                        new
                        {
                            Id = 16,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 42
                        },
                        new
                        {
                            Id = 17,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 43
                        },
                        new
                        {
                            Id = 18,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 50
                        },
                        new
                        {
                            Id = 19,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 51
                        },
                        new
                        {
                            Id = 20,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 52
                        },
                        new
                        {
                            Id = 21,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 60
                        },
                        new
                        {
                            Id = 22,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 61
                        },
                        new
                        {
                            Id = 23,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 70
                        },
                        new
                        {
                            Id = 24,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 71
                        },
                        new
                        {
                            Id = 25,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 72
                        },
                        new
                        {
                            Id = 26,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 73
                        },
                        new
                        {
                            Id = 27,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 80
                        },
                        new
                        {
                            Id = 28,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 1,
                            YetkiTanimiId = 81
                        },
                        new
                        {
                            Id = 29,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 1
                        },
                        new
                        {
                            Id = 30,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 10
                        },
                        new
                        {
                            Id = 31,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 11
                        },
                        new
                        {
                            Id = 32,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 12
                        },
                        new
                        {
                            Id = 33,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 20
                        },
                        new
                        {
                            Id = 34,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 21
                        },
                        new
                        {
                            Id = 35,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 22
                        },
                        new
                        {
                            Id = 36,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 30
                        },
                        new
                        {
                            Id = 37,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 31
                        },
                        new
                        {
                            Id = 38,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 32
                        },
                        new
                        {
                            Id = 39,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 40
                        },
                        new
                        {
                            Id = 40,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 41
                        },
                        new
                        {
                            Id = 41,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 42
                        },
                        new
                        {
                            Id = 42,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 50
                        },
                        new
                        {
                            Id = 43,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 51
                        },
                        new
                        {
                            Id = 44,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 2,
                            YetkiTanimiId = 52
                        },
                        new
                        {
                            Id = 45,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 1
                        },
                        new
                        {
                            Id = 46,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 10
                        },
                        new
                        {
                            Id = 47,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 20
                        },
                        new
                        {
                            Id = 48,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 30
                        },
                        new
                        {
                            Id = 49,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 40
                        },
                        new
                        {
                            Id = 50,
                            AktifMi = true,
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolId = 3,
                            YetkiTanimiId = 50
                        });
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UyeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UyeAdiSoyadi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UyeAdiSoyadi");

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.YetkiTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YetkiTanimiId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("MenuYetkisiMi")
                        .HasColumnType("bit");

                    b.Property<string>("ModulKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("YetkiKodu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("YetkiKodu")
                        .IsUnique();

                    b.ToTable("YetkiTanimlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Dashboard",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 1,
                            YetkiAdi = "Dashboard Görüntüle",
                            YetkiKodu = "Dashboard.View"
                        },
                        new
                        {
                            Id = 10,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Books",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 10,
                            YetkiAdi = "Kitapları Görüntüle",
                            YetkiKodu = "Books.View"
                        },
                        new
                        {
                            Id = 11,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Books",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 11,
                            YetkiAdi = "Kitap Ekle",
                            YetkiKodu = "Books.Create"
                        },
                        new
                        {
                            Id = 12,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Books",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 12,
                            YetkiAdi = "Kitap Düzenle",
                            YetkiKodu = "Books.Edit"
                        },
                        new
                        {
                            Id = 13,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Books",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 13,
                            YetkiAdi = "Kitap Sil",
                            YetkiKodu = "Books.Delete"
                        },
                        new
                        {
                            Id = 20,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Members",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 20,
                            YetkiAdi = "Üyeleri Görüntüle",
                            YetkiKodu = "Members.View"
                        },
                        new
                        {
                            Id = 21,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Members",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 21,
                            YetkiAdi = "Üye Ekle",
                            YetkiKodu = "Members.Create"
                        },
                        new
                        {
                            Id = 22,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Members",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 22,
                            YetkiAdi = "Üye Düzenle",
                            YetkiKodu = "Members.Edit"
                        },
                        new
                        {
                            Id = 23,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Members",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 23,
                            YetkiAdi = "Üye Sil",
                            YetkiKodu = "Members.Delete"
                        },
                        new
                        {
                            Id = 30,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Loans",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 30,
                            YetkiAdi = "Ödünçleri Görüntüle",
                            YetkiKodu = "Loans.View"
                        },
                        new
                        {
                            Id = 31,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Loans",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 31,
                            YetkiAdi = "Ödünç Ver",
                            YetkiKodu = "Loans.Create"
                        },
                        new
                        {
                            Id = 32,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Loans",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 32,
                            YetkiAdi = "İade Al",
                            YetkiKodu = "Loans.Return"
                        },
                        new
                        {
                            Id = 33,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Loans",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 33,
                            YetkiAdi = "Ödünç İptal Et",
                            YetkiKodu = "Loans.Cancel"
                        },
                        new
                        {
                            Id = 40,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "BookCopies",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 40,
                            YetkiAdi = "Kitap Kopyalarını Görüntüle",
                            YetkiKodu = "BookCopies.View"
                        },
                        new
                        {
                            Id = 41,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "BookCopies",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 41,
                            YetkiAdi = "Kitap Kopyası Ekle",
                            YetkiKodu = "BookCopies.Create"
                        },
                        new
                        {
                            Id = 42,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "BookCopies",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 42,
                            YetkiAdi = "Kitap Kopyası Düzenle",
                            YetkiKodu = "BookCopies.Edit"
                        },
                        new
                        {
                            Id = 43,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "BookCopies",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 43,
                            YetkiAdi = "Kitap Kopyası Sil",
                            YetkiKodu = "BookCopies.Delete"
                        },
                        new
                        {
                            Id = 50,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Reports",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 50,
                            YetkiAdi = "Raporları Görüntüle",
                            YetkiKodu = "Reports.View"
                        },
                        new
                        {
                            Id = 51,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Reports",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 51,
                            YetkiAdi = "Rapor Yazdır",
                            YetkiKodu = "Reports.Print"
                        },
                        new
                        {
                            Id = 52,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Reports",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 52,
                            YetkiAdi = "Rapor Dışa Aktar",
                            YetkiKodu = "Reports.Export"
                        },
                        new
                        {
                            Id = 60,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "FormFields",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 60,
                            YetkiAdi = "Form Alanlarını Görüntüle",
                            YetkiKodu = "FormFields.View"
                        },
                        new
                        {
                            Id = 61,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "FormFields",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 61,
                            YetkiAdi = "Form Alanı Düzenle",
                            YetkiKodu = "FormFields.Edit"
                        },
                        new
                        {
                            Id = 70,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Users",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 70,
                            YetkiAdi = "Kullanıcıları Görüntüle",
                            YetkiKodu = "Users.View"
                        },
                        new
                        {
                            Id = 71,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Users",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 71,
                            YetkiAdi = "Kullanıcı Ekle",
                            YetkiKodu = "Users.Create"
                        },
                        new
                        {
                            Id = 72,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Users",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 72,
                            YetkiAdi = "Kullanıcı Düzenle",
                            YetkiKodu = "Users.Edit"
                        },
                        new
                        {
                            Id = 73,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Users",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 73,
                            YetkiAdi = "Kullanıcı Rol Yönet",
                            YetkiKodu = "Users.RoleManage"
                        },
                        new
                        {
                            Id = 80,
                            AktifMi = true,
                            MenuYetkisiMi = true,
                            ModulKodu = "Permissions",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 80,
                            YetkiAdi = "Yetkileri Görüntüle",
                            YetkiKodu = "Permissions.View"
                        },
                        new
                        {
                            Id = 81,
                            AktifMi = true,
                            MenuYetkisiMi = false,
                            ModulKodu = "Permissions",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SiraNo = 81,
                            YetkiAdi = "Yetki Yönet",
                            YetkiKodu = "Permissions.Manage"
                        });
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.DinamikAlanDegeri", b =>
                {
                    b.HasOne("NexLibrary.Domain.Entities.FormAlani", "FormAlani")
                        .WithMany("DinamikAlanDegerleri")
                        .HasForeignKey("FormAlaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormAlani");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.KitapKopya", b =>
                {
                    b.HasOne("NexLibrary.Domain.Entities.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kitap");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.KullaniciRol", b =>
                {
                    b.HasOne("NexLibrary.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexLibrary.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Odunc", b =>
                {
                    b.HasOne("NexLibrary.Domain.Entities.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexLibrary.Domain.Entities.KitapKopya", "KitapKopya")
                        .WithMany()
                        .HasForeignKey("KitapKopyaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexLibrary.Domain.Entities.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("KitapKopya");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.RolYetki", b =>
                {
                    b.HasOne("NexLibrary.Domain.Entities.Rol", "Rol")
                        .WithMany("RolYetkileri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexLibrary.Domain.Entities.YetkiTanimi", "YetkiTanimi")
                        .WithMany("RolYetkileri")
                        .HasForeignKey("YetkiTanimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("YetkiTanimi");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.FormAlani", b =>
                {
                    b.Navigation("DinamikAlanDegerleri");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");

                    b.Navigation("RolYetkileri");
                });

            modelBuilder.Entity("NexLibrary.Domain.Entities.YetkiTanimi", b =>
                {
                    b.Navigation("RolYetkileri");
                });
#pragma warning restore 612, 618
        }
    }
}
